### ISSUE TITLE
Scraping de dados errado

### ISSUE THREAD

**Issue by polotto** [dennnisk/loterias-caixa-json#1]
Eu utilizei essa biblioteca (versão da biblioteca: 1.0.2) em um projeto de teste e vi que ela está fazendo o scraping de dados errado:

JSON gerado pela biblioteca para o segundo concurso:
{"Concurso":2,
"DataSorteio":"18/03/1996",
"Dezena1":9,
"Dezena2":39,
"Dezena4":49,
"Dezena5":43,
"Dezena3":37,
"Dezena6":41,
"Arrecadacao_Total":0,
"Ganhadores_Sena":1,
"Cidade":"2.307.162,23",
"UF":"65",
"Rateio_Sena":14424.02,
"Ganhadores_Quina":4488,
"Rateio_Quina":208.91,
"Ganhadores_Quadra":null,
"Rateio_Quadra":0,
"Acumulado":0,
"Valor_Acumulado":0,
"Estimativa_Prêmio":null,
"Acumulado_Mega_da_Virada":null }

Dados retirados do HTML da caixa para o segundo concurso:
Concurso | 2 
Data Sorteio | 18/03/1996 |
1ª Dezena | 09 
2ª Dezena | 39 
3ª Dezena | 37 
4ª Dezena | 49 
5ª Dezena | 43 
6ª Dezena | 41 
Arrecadacao_Total | 0,00 
Ganhadores_Sena | 1 
Cidade | 
UF | PR 
 Rateio_Sena | 2.307.162,23 
Ganhadores_Quina | 65 
Rateio_Quina | 14.424,02 
Ganhadores_Quadra | 4488 
Rateio_Quadra |  208,91 
Acumulado | NÃO
Valor_Acumulado | 0,00
Estimativa_Prêmio | 0,00
Acumulado_Mega_da_Virada | 0,00

Como pode ver, a partir do campo Cidade, os dados estão em na ordem errada, acredito q seja algo relacionado ao scraping da tabela.

**Comment by dennnisk** [comment]
Obrigado pelo report, vou verificar.

**Comment by angelopolotto** [comment]
Por nada, quando resolver, deixe um comentário aqui para eu pegar a última versão.

**Comment by dennnisk** [comment]
Depois de muito tempo fiz a correção e disponibilizei.
